### ISSUE TITLE
As a user, I want to run through a deck so that I can review my knowledge of the topic

### ISSUE THREAD

**Issue by yujiatay** [CS2103-AY1819S1-T09-2/main#120]
- [X] `review` command + gameplay UI
- [X] iterate through cards
- [x] indicate performance
- [ ] resume from save point
